### ISSUE TITLE
[열차변경] EMU-150 스프라이트 변경

### ISSUE THREAD

**Issue by Gamunbi** [GBLINER/KoreanTrainSet_Plus#3]
==========[필수스프라이트]==========
![전동차 220000호대 - ITX-새마을 KTS+ 적색 1차 완성](https://user-images.githubusercontent.com/75788864/172011425-398b4f87-abb6-41f5-8b6d-9d7c7e55cfc1.png)

![전동차 220000호대 - ITX-새마을 KTS+ 녹색 1차 완성](https://user-images.githubusercontent.com/75788864/172011429-1f0694a7-ef34-4fc3-bd83-2174d25acfc7.png)

==========[설명]==========
최근에 실물이 공개돼서 크게 수정해보았습니다. YST에 있던 기존의 스프라이트 사이즈에 따라 조정한 것입니다. 

바뀐부분은 주로 흰 줄무늬, 지붕 디테일, 팬터그래프 방향과 디테일, 대차 등 열차 밑부분 디테일입니다.

거슬리지 않으시다면 그대로 쓰시면 됩니다.

==========[YST적용내용]==========
적용될 기존 열차 이름 : EMU-150

**Comment by GBLINER** [comment]
안녕하세요 가문비님! 
먼저 가문비님이 제작하신 한국 트램셋과 한국 선로셋들을 잘 사용하고 있습니다. 

개인적으로는 GRF제작자로서 트램과 선로 쪽이라는 새로운 분야에 GRF를 제작하시는것을 보면서 약간의 존경심이 듭니다...!
 저도 한국 항공기 세트를 개발함으로서 한국 NewGRF의 새로운 분야를 개척해 나가고 있지요...

https://discord.gg/7dqvzh2ABU

저와 YST의 개발자이신 Me Making님을 비롯하여 여러명의 개발자들이 있습니다. 부담스럽지 않으시다면 이 디스코드에서 같이 소통하셔도 괜찮으실까요? 코딩을 비롯하여 스프라이트 제작자 분들도 계십니다. 개인적으로는 NewGRF 개발에 대한 노하우나 기술적인 부분도 공유해보고 싶습니다

그리고 이슈에 올려주신 스프라이트는 오늘(일요일) 낮쯤 코딩해서 내일 오후쯤 Bananas에 바로 업데이트를 하도록 하겠습니다. 역시 트램셋을 개발하셔서 그런지 스프라이트 퀄리티가 어우... 매우 좋습니다.

**Comment by Gamunbi** [comment]
스프라이트 좋게 봐주셔서 감사합니다. 디스코드에 들어가보겠습니다.

**Comment by Gamunbi** [comment]
![전동차 220000호대 - ITX-새마을 KTS+ 적색 1차 완성 32bpp](https://user-images.githubusercontent.com/75788864/172058864-77768c3c-bdb5-43ed-8710-f863f1e623d3.png)
![전동차 220000호대 - ITX-새마을 KTS+ 녹색 1차 완성 32bpp](https://user-images.githubusercontent.com/75788864/172058865-06bdf9cb-6bbe-477a-8d3e-46a3ad8ea94e.png)

32bpp 버전입니다. 어두운 부분이 좀 더 어둡습니다.

**Comment by GBLINER** [comment]
32bpp 까지 적용완료
